export const GET_PRODUCT="GET_PRODUCT"
export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_TO_CART="REMOVE_TO_CART"
export const CHECK_OUT="CHECK_OUT"
export const REGISTER_DATA="REGISTER_DATA"
export const LOGIN_USER="LOGIN_USER"
export const BUY_NOW="BUY_NOW"
export const LOGOUT="LOGOUT"